app/models.py
from app import db


# Creating table using pythonic way
class Task(db.Model):
    id = db.Column(db.Integer, primary_key = True)
    title = db.Column(db.String(100), nullable = False)
    status = db.Column(db.String(50), default = 'pending')

    user_id = db.Column(db.Integer, db.ForeignKey('register.id'), nullable=False)
    

class Register(db.Model):
    id = db.Column(db.Integer, primary_key = True)
    username = db.Column(db.String(30), unique = True, nullable = False)
    password = db.Column(db.String(30),  nullable = False)

    task = db.relationship('Task', backref='register', lazy=True)

    

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()  # Creating database object

def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'secret'
    # app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///todo.db'   
    #if use mysql : Make sure "To_do_app" database already created
    app.config['SQLALCHEMY_DATABASE_URI'] = 'mysql+pymysql://root:2266@localhost/to_do_app'
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

    db.__init__(app)  # Connect to database


    # all routes connect to app:
    from app.routes.auth import auth_bp
    from app.routes.task import task_bp
    app.register_blueprint(auth_bp)
    app.register_blueprint(task_bp)

    return app

app/routes/auth.py
from flask import Blueprint, request, render_template, session, url_for, redirect, flash
from app.models import Register
from app import db

auth_bp = Blueprint('auth', __name__)


@auth_bp.route('/login', methods = ['GET', 'POST'])
def login():
    if request.method == 'POST':
        # inputs from user:
        username = request.form.get('username')
        password = request.form.get('password')

        # exits user:
        user = Register.query.filter_by(username = username).first()

        if user:
            if password == user.password:
                session['user_id'] = user.id
                session['user'] = user.username
                flash('Login successful!', 'success')
                return redirect(url_for('task.view_task'))
            else:
                flash('Please enter correct username and password.', 'danger')
        else:
            flash('User not available, Please sign up.', 'danger')
            return redirect(url_for('auth.sign_up'))
    return render_template('login.html')

@auth_bp.route('/logout')
def logout():
    session.pop('user', None)
    session.pop('user_id', None)
    flash('Logged out Successfully','info')
    return redirect(url_for('auth.login'))

@auth_bp.route('/sign_up')
def sign_up():
    return render_template('register.html')

@auth_bp.route('/register', methods = ['POST'])
def register():
    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')
        con_password = request.form.get('confirm-password')

        if not(password == con_password):
            flash('Password mismatch. Try again!', 'danger')
            return redirect(url_for('auth.sign_up'))
        else:
            existing_user = Register.query.filter_by(username = username).first()  # For Unique username
            if existing_user:
                flash("Username not available!", 'danger')
                return redirect(url_for('auth.sign_up'))
            else:
                new_user = Register(username = username, password = password)
                db.session.add(new_user)
                db.session.commit()
                flash('Successfully signed in.', 'success')

    return redirect(url_for('auth.login'))

app/routes/task.py
from flask import Blueprint, render_template, request, redirect, url_for, session, flash
from app import db
from app.models import Task

task_bp = Blueprint('task', __name__)

# CRUD Operation


# Retrive/ Read:
@task_bp.route('/')
def view_task():
    if 'user' not in session:  #If user not logged in
        return redirect(url_for('auth.login'))

    user_id = session['user_id']
    task = Task.query.filter_by(user_id=user_id).all()
    return render_template('task.html', task = task, name = session['user'])


# Create :
@task_bp.route('/add', methods = ['POST'])
def add_task():
    if 'user' not in session:    #If user not logged in
        return redirect(url_for('auth.login'))

    title = request.form.get('title')
    user_id = session['user_id']

    if title:
        new_task = Task(title = title, user_id = user_id)
        db.session.add(new_task)
        db.session.commit()
        flash(f'Task {title} added successfully.', 'success')

    return redirect(url_for('task.view_task'))


# Update :
@task_bp.route('/toggle/<int:task_id>')
def update_status(task_id):    
    task = Task.query.get(task_id)
    if task:
        if task.status == 'pending':
            task.status = 'working'
        elif task.status == 'working':
            task.status = 'done'
        else:
            task.status = 'pending'
        db.session.commit()
    return redirect(url_for('task.view_task'))

# Delete :
@task_bp.route('/clear_all')
def clear_all():
    Task.query.delete()
    db.session.commit()
    flash('All tasks cleared!', 'info')
    return redirect(url_for('task.view_task'))

# Clear task :
@task_bp.route('/clear_task/<int:task_id>')
def clear_task(task_id):    
    task = Task.query.get(task_id)
    if task:
        flash(f'Task {task.title} removed successfully!', 'info')
        db.session.delete(task)
        db.session.commit()
    
    return redirect(url_for('task.view_task'))

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} Todo app {% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css')}}">
</head>
<body>
    <header>
        <div class="container">
            <h1>My Todo App</h1>
            <nav>
                <a href="{{ url_for('task.view_task')}}">Home</a>
                {% if 'user' in session %}
                <a href="{{ url_for('auth.logout') }}">Log out</a>
                {% else %}
                <a href="{{ url_for('auth.login') }}">Log in</a>
                {% endif %}
            </nav>
        </div>
    </header>
    <main class="container">
        {% with messages = get_flashed_messages(with_categories = True) %}
            {% for category, msg in messages %}
                <div class="flash {{category}}">{{msg}}</div>
            {% endfor %}
        {% endwith %}

        {% block content %}
        {% endblock %}
    </main>
    <footer>
        <div class="container">
            <p>&copy; 2025, All rights reserved.</p>
        </div>
    </footer>
</body>
<script src="{{ url_for('static', filename='js/scripts.css')}}"></script>
</html>

app/templates/login.html
{% extends 'base.html' %}
{% block title %}Log in{% endblock %}

{% block content %}

<div class="login-box">
    <h2>Log in</h2>
    <form action="{{ url_for('auth.login') }}" method="POST">
        <div class="form-group">
            <label for="username">Username</label>
            <input type="text" name="username" id="username" required>
        </div>
        <div class="form-group">
            <label for="password">password</label>
            <input type="password" name="password" id="password" required>
        </div>
        <button type="submit" class="btn">Login</button>
        <br><br>
    </form>
    <div class="sign-up">
        <p>Don't have an account? <a href="{{ url_for('auth.sign_up') }}">Sign up</a></p>
    </div>
</div>

{% endblock %}

app/templates/register.html
{% extends 'base.html'%}
{% block title %}Register{% endblock %}

{% block content %}
<div class="login-box">
    <h2>Registration</h2>
    <form action="{{ url_for('auth.register') }}" method="POST">
        <div class="form-group">
            <label for="username">Username</label>
            <input type="text" name="username" id="username" required>
        </div>
        <div class="form-group">
            <label for="password">Password</label>
            <input type="password" name="password" id="password" required>
        </div>
        <div class="form-group">
            <label for="confirm-password">Confirm password</label>
            <input type="password" name="confirm-password" id="confirm-password" required>
        </div>
        <button type="submit" class="btn">Sign up</button>
        <br><br>
    </form>
    <div class="sign-up">
        <a href="{{ url_for('auth.login') }}">Log in</a>
    </div>
</div>

{% endblock %}

app/templates/task.html
{% extends 'base.html'%}
{% block title %}Tasks{% endblock %}

{% block content %}

<div class="task-box">
    <h2>Welcome {{ name }}! your Tasks are:</h2>
    <form action="{{ url_for('task.add_task') }}" method="POST" class="task-form">
        <input type="text" name="title" placeholder="New task" required>
        <button type="submit" class="btn">Add</button>
    </form>

    {% if task %}
    <form action="{{ url_for('task.clear_all') }}">
        <button type="submit" class="btn btn-clear">Clear All</button>
    </form>

    <br>

    <table class="task-table">
        <thead>
            <tr>
                <th></th>
                <th>Task</th>
                <th>Status</th>
                <th>Change</th>
                <th>Clear task</th>
            </tr>
        </thead>
        <tbody>
            {%for i in task %}
            <tr>
                <td>{{ loop.index }}</td>
                <td>{{ i.title }}</td>
                <td>
                    <span class="badge {{ i.status|lower }}">{{ i.status }}</span>
                </td>
                <td>
                    <form action="{{ url_for('task.update_status', task_id = i.id )}}">
                        <button type="submit" class="btn-small">Next</button>
                    </form>
                </td>
                <td>
                    <form action="{{ url_for('task.clear_task', task_id = i.id )}}">
                        <button type="submit" class="btn-clear-task">Clear</button>
                    </form>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
    <p>No task yet!</p>
    {% endif %}
</div>
{% endblock %}